### ISSUE TITLE
Help to customize and make responsive UI

### ISSUE THREAD

**Issue by sonadztux** [sonadztux/eid_mubarak_html_template#2]
Hello, everyone. This repo is open for contribution and welcome for hacktoberfest participants. The main issue is the interface still not responsive to mobile, just make PR about this issue. Thanks in advance

**Comment by rabsonj** [comment]
Can you please assign me this issue?

And the website demo is not working

**Comment by sonadztux** [comment]
> Can you please assign me this issue?
> 
> And the website demo is not working

Of course. Oh ya, I forgot to mention that the demo website is not online anymore. Can you help to serve for the demo website too?

**Comment by rabsonj** [comment]
> > Can you please assign me this issue?
> > And the website demo is not working
> 
> Of course. Oh ya, I forgot to mention that the demo website is not online anymore. Can you help to serve for the demo website too?

The demo can be hosted on github pages. Let me work on it

**Comment by sonadztux** [comment]
> The demo can be hosted on github pages. Let me work on it

Just go on. Anyway, thank you so much bro @RabsonJ

**Comment by rabsonj** [comment]
Hey @sonadztux I made the terminal more responsive. I have included the demo site for you to view it on a smaller device. I'm hosting it on my GitHub Pages but I'll remove it later because it's only for demo purposes

**Comment by rabsonj** [comment]
Also, can you help me by adding the **hacktoberfest accepted** label so that it may count towards my contribution

**Comment by sonadztux** [comment]
> Also, can you help me by adding the **hacktoberfest accepted** label so that it may count towards my contribution

Label added. I'll review it and merged it as soon as I'm home.

**Comment by sonadztux** [comment]
PR merged. Nice work! Thank you @RabsonJ

**Comment by rabsonj** [comment]
> PR merged. Nice work! Thank you @RabsonJ

My pleasure
